/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.example.test_without_webhooks;

import com.example.test_without_webhooks.utils.HTTPClient;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "v1";
	public String sdkVersion = "0.6.0";
	public String genVersion = "2.154.1";
	public String userAgent = "speakeasy-sdk/java 0.6.0 2.154.1 v1 <no value>";
	
	
}