/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.example.test_without_webhooks.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class Pet1 {
    @JsonProperty("id")
    public Long id;

    public Pet1 withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public Pet1 withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tag")
    public String tag;

    public Pet1 withTag(String tag) {
        this.tag = tag;
        return this;
    }
    
    public Pet1(@JsonProperty("id") Long id, @JsonProperty("name") String name) {
        this.id = id;
        this.name = name;
  }
}
