/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.example.test_without_webhooks.utils;

import java.net.http.HttpRequest.BodyPublisher;

public class SerializedBody {
    public String contentType;
    public BodyPublisher body;
}
